name: "helm-test"
version: "0.0.1"
usage: "Plugin test"
description: "Plugin test"
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/helm-test"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh -u"