name: "helm-test"
version: "0.0.3"
usage: "Plugin test"
description: "Plugin test"
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/helm-test"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
